(define (domain ffmpeg)
        (:requirements :equality)
        (:constants Libx264 Libx265 Aac Opus)
        (:predicates
            (file ?a)
            (name ?a)
            (have ?a ?b)
            (stream ?s)
            (encode ?c ?s)
            (opened ?f))
        (:action OPEN_FILE
            :parameters (?f ?n)
            :precondition (and (file ?f)
                               (name ?n)
                               (have ?f ?n))
            :effect (opened ?f))
        (:action WRITE_FILE
            :parameters (?f ?n)
            :vars (?m)
            :precondition (and (opened ?m)
                               (not (or (file ?f)
                                        (name ?n)
                                        (have ?f ?n))))
            :effect (and (file ?f)
                         (name ?n)
                         (have ?f ?n))))
