(define (domain ffmpeg)
        (:requirements :equality)
        (:constants Libx264 Libx265 Aac Opus)
        (:predicates
            (dupa)
            (file ?a)
            (name ?a)
            (have ?a ?b))
        (:action OPEN_FILE
            :parameters (?f ?n)
            :precondition (not (or (file ?f)
                                   (name ?n)
                                   (have ?f ?n)))
            :effect (and (file ?f)
                         (name ?n)
                         (have ?f ?n))))
